Minor fixes since MISC-1 has been fixed already.

diff --git a/tarit b/tarit
--- a/tarit
+++ b/tarit
@@ -67,20 +67,16 @@ if [ -d $unslashed ] ; then
 
 	echo "Creating tar archive"
 	tar cf $unslashed.tar $unslashed
-
 	if [ "$?" != "0" ] ; then
 		echo "Something failed during the tar session. I will not continue."
 		exit
 	fi
-
 	$preferred $params $unslashed.tar
-
 	if [ -f $packed ] ; then
 		echo "Compressed archive, $packed, seems to be created. Finalize by removal!"
 		rm -rf $unslashed
 		echo "Done."
 	fi
-
 else
 	if [ -f $unslashed ] ; then
 		allowedExtensions="zip:unzip rar:rar tgz:tar tar:tar txz:tar tbz:tar tbz2:tar"
@@ -110,46 +106,46 @@ else
 			echo "This is a file is unsupported"
 			exit
 		fi
-
 		if [ "$filePacker" != "" ] && [ -f $filePacker ] && [ "$currentExtension" != "" ] ; then
 			unExtend=`echo $unslashed | sed "s/\.$currentExtension$//g"`
 			tarArchive="$unExtend.tar";
 			tarFolder="$tarArchive.\$tmp\$"
 			echo "RePack $unExtend(.$currentExtension) => $tarArchive ($tarFolder)"
-			if [ -d $tarFolder ] ; then
-				echo "Cleaning up"
+			if [ "$tarFolder" != "" ] && [ -d $tarFolder ] ; then
+				echo "Clean up."
 				rm -rfv $tarFolder
 			fi
 			if [ ! -d $tarFolder ] && [ ! -f $tarArchive ] && [ ! -f $tarArchive.$extension ] ; then
-				mkdir $tarFolder
 				echo "Creating $tarFolder"
-				cd $tarFolder
-				doExtract="$filePacker $extractCmd ../$unExtend.$currentExtension"
-				echo $doExtract
-				$doExtract
-				if [ "$?" != "0" ] ; then
-					echo "The extracting archiver gave me an errorcode ($?) that made me stop the process"
-					exit
-				fi
-				echo "Calculating size of directory"
-				dirsize=`du -h . | tail -1 | awk '{printf \$1}'`
-				echo "Directory size: $dirsize - beginning the tar session"
-				tar cf ../$tarArchive .
-
-				if [ "$?" != "0" ] ; then
-					echo "The tar archiving process failed to succeed. Packing process aborted."
-					exit
-				fi
-
-				cd ..
-				echo "Compress: $preferred $params $tarArchive"
-				if [ -f $tarArchive ] && [ ! -f $tarArchive.$extension ] ; then
-					rm -rf $tarFolder
-					$preferred $params $tarArchive
-					echo "Comparision:"
-					ls -l $unExtend.*
-					echo "Cleaning up"
-					rm -v $unExtend.$currentExtension
+				mkdir $tarFolder
+				# Make sure it actually worked
+				if [ -d $tarFolder] ; then
+					cd $tarFolder
+					doExtract="$filePacker $extractCmd ../$unExtend.$currentExtension"
+					echo $doExtract
+					$doExtract
+					if [ "$?" != "0" ] ; then
+						echo "The extracting archiver gave me an errorcode ($?) that made me stop the process"
+						exit
+					fi
+					echo "Calculating size of directory"
+					dirsize=`du -h . | tail -1 | awk '{printf \$1}'`
+					echo "Directory size: $dirsize - beginning the tar session"
+					tar cf ../$tarArchive .
+					if [ "$?" != "0" ] ; then
+						echo "The tar archiving process failed to succeed. Packing process aborted."
+						exit
+					fi
+					cd ..
+					echo "Compress: $preferred $params $tarArchive"
+					if [ -f $tarArchive ] && [ ! -f $tarArchive.$extension ] ; then
+						rm -rf $tarFolder
+						$preferred $params $tarArchive
+						echo "Comparision:"
+						ls -l $unExtend.*
+						echo "Cleaning up"
+						rm -v $unExtend.$currentExtension
+					fi
 				fi
 			else
 				echo "$tarArchive (or the packed one) already exists in this folder."
